import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Config } from "./config.js";

/**
 * The editor apps (Codex / Claude Code desktop) spawn MCP servers with a minimal PATH that
 * does NOT include nvm/homebrew bin dirs — so a bare `embarsy-mcp` command fails to launch.
 * We sidestep that entirely by writing ABSOLUTE paths: the current `node` binary + the
 * absolute path to this package's compiled mcp.js.
 */
function resolveSpawn(): { command: string; args: string[] } {
  const mcpJs = fileURLToPath(new URL("./bin/mcp.js", import.meta.url));
  return { command: process.execPath, args: [mcpJs] };
}

/** Env block written into the editor config so the server has everything it needs.
 *  `EMBARSY_CLIENT` is the only way Embarsy can ever name the editor: Claude Code and
 *  Codex spawn the identical binary, so the editor is knowable only here, at the moment
 *  we write the config FOR a specific one. */
function serverEnv(cfg: Config, client: string): Record<string, string> {
  // A collection is deliberately NOT pinned unless the user asked for one: left out, the
  // server resolves it from the directory the editor is working in, so one registration
  // serves every indexed project instead of just the one that happened to be current here.
  const pinned: Record<string, string> = cfg.collection
    ? { QDRANT_COLLECTION_NAME: cfg.collection }
    : {};
  return {
    ...pinned,
    EMBARSY_CLIENT: client,
    OPENAI_BASE_URL: cfg.openaiBaseUrl,
    OPENAI_API_KEY: cfg.openaiApiKey,
    EMBEDDING_MODEL: cfg.embeddingModel,
    EMBEDDING_DIMENSION: String(cfg.embeddingDimension),
    QDRANT_URL: cfg.qdrantUrl,
    QDRANT_API_KEY: cfg.qdrantApiKey,
  };
}

const SERVER_NAME = "embarsy-qdrant";

/** Write the `[mcp_servers.embarsy-qdrant]` block into ~/.codex/config.toml (respects
 *  $CODEX_HOME). Codex reads one config for every directory, so this is already machine-wide.
 *
 *  Re-running REPLACES our own block rather than failing: keys are regenerated by a reinstall,
 *  and telling someone to hand-edit a TOML file to recover is exactly the kind of step this
 *  command exists to remove. Blocks belonging to other servers are left untouched. */
export async function setupCodex(cfg: Config): Promise<string> {
  const home = process.env.CODEX_HOME || path.join(os.homedir(), ".codex");
  await fs.mkdir(home, { recursive: true });
  const file = path.join(home, "config.toml");
  const existing = stripOwnTomlBlock(await readOrEmpty(file));
  const { command, args } = resolveSpawn();
  const env = serverEnv(cfg, "codex");
  const lines = [
    "",
    `[mcp_servers.${SERVER_NAME}]`,
    `command = ${toml(command)}`,
    `args = [${args.map(toml).join(", ")}]`,
    "",
    `[mcp_servers.${SERVER_NAME}.env]`,
    ...Object.entries(env).map(([k, v]) => `${k} = ${toml(v)}`),
    "",
  ];
  const next = (existing.trimEnd() + "\n" + lines.join("\n")).replace(/^\n+/, "");
  await fs.writeFile(file, next, "utf8");
  return file;
}

export type ClaudeScope = "user" | "project";

/** Register the `embarsy-qdrant` server for Claude Code.
 *
 *  Defaults to USER scope (`~/.claude.json`), because project scope has a trap that is
 *  invisible from the outside: a `.mcp.json` is found by walking up from the session's
 *  directory, but each directory must separately APPROVE the server before it loads. Open a
 *  subproject of the workspace you ran this in and the index is silently absent — everything
 *  looks configured and nothing works. User scope is the user's own config: available in
 *  every directory, nothing to approve.
 *
 *  Project scope stays available for the case it is actually right: a repo whose `.mcp.json`
 *  is committed so the whole team gets it. */
export async function setupClaude(cfg: Config, scope: ClaudeScope = "user"): Promise<string> {
  const file = scope === "user" ? path.join(os.homedir(), ".claude.json") : path.resolve(".mcp.json");
  let json: any = {};
  const existing = await readOrEmpty(file);
  if (existing.trim()) {
    try { json = JSON.parse(existing); } catch { throw new Error(`${file} is not valid JSON — fix or remove it first.`); }
  }
  if (typeof json !== "object" || json === null) json = {};

  // `~/.claude.json` is Claude Code's live config and holds far more than MCP servers, so
  // every other key is preserved untouched and the file is replaced atomically — a half
  // written config here would break the editor itself, not just this integration.
  json.mcpServers = json.mcpServers ?? {};
  const { command, args } = resolveSpawn();
  json.mcpServers[SERVER_NAME] = { command, args, env: serverEnv(cfg, "claude-code") };

  if (scope === "user" && existing.trim()) {
    await fs.writeFile(`${file}.embarsy-backup`, existing, "utf8");
  }
  await writeAtomic(file, JSON.stringify(json, null, 2) + "\n");
  return file;
}

/** Remove our own `[mcp_servers.embarsy-qdrant]` + `.env` blocks, leaving every other
 *  section exactly as it was. A TOML section runs until the next `[header]` or EOF. */
function stripOwnTomlBlock(source: string): string {
  const lines = source.split("\n");
  const out: string[] = [];
  let skipping = false;
  for (const line of lines) {
    const header = /^\s*\[([^\]]+)\]/.exec(line);
    if (header) {
      const name = header[1]!;
      skipping = name === `mcp_servers.${SERVER_NAME}` || name.startsWith(`mcp_servers.${SERVER_NAME}.`);
    }
    if (!skipping) out.push(line);
  }
  return out.join("\n");
}

async function writeAtomic(file: string, contents: string): Promise<void> {
  const tmp = `${file}.embarsy-tmp-${process.pid}`;
  await fs.writeFile(tmp, contents, "utf8");
  await fs.rename(tmp, file);
}

async function readOrEmpty(file: string): Promise<string> {
  try { return await fs.readFile(file, "utf8"); } catch { return ""; }
}

/** Minimal TOML basic-string quoting (JSON escaping is a valid superset for our values). */
function toml(value: string): string {
  return JSON.stringify(value);
}
