import Foundation

/// Renders a benchmark run into a human-readable Markdown log: every query, the exact
/// commands, per-engine timings, ranked files and context sizes. The audience is a
/// skeptical developer — the log must let them re-run everything by hand, so it
/// favours verifiable facts (commands, counts, paths) over narrative.
enum BenchmarkLogComposer {

    static func compose(
        result: RetrievalBenchmark,
        lastRun: Date?,
        duels: [AgentDuel],
        duelEditor: BenchmarkEditor?
    ) -> String {
        var out: [String] = []
        out.append("# Embarsy benchmark log")
        out.append("")
        let stamp = (lastRun ?? Date()).formatted(date: .long, time: .standard)
        out.append("- Generated by Embarsy \(EmbarsyBuildInfo.shortVersion) (build \(EmbarsyBuildInfo.bundleVersion)) on \(stamp)")
        out.append("- Collection: `\(result.collection)` · Workspace: `\(result.workspacePath)`")
        if let root = result.grepRoot, root != result.workspacePath {
            out.append("- Search scope for BOTH engines: `\(root)` — the root of the indexed tree, detected from the sampled files (grep is never made to scan sibling projects the index doesn't cover)")
        }
        out.append("- \(result.samples) questions · an engine scores a hit when the ground-truth file is in its top-\(result.topK)\(result.paraphrased == true ? " · **synonym mode**" : "")")
        if let skipped = result.skippedErrors, skipped > 0 {
            out.append("- \(skipped) sampled question\(skipped == 1 ? "" : "s") skipped because the embedding backend errored — skipped rows count for neither engine")
        }
        out.append("")

        out.append(contentsOf: methodology(result))
        out.append(contentsOf: verdict(result))

        out.append("## Question by question")
        out.append("")
        for (index, row) in result.queries.enumerated() {
            out.append(contentsOf: questionSection(index: index, row: row, topK: result.topK))
        }

        if !duels.isEmpty, let editor = duelEditor {
            out.append(contentsOf: duelSection(duels: duels, editor: editor))
        }

        out.append(contentsOf: notes(result))
        return out.joined(separator: "\n")
    }

    // MARK: Sections

    private static func methodology(_ result: RetrievalBenchmark) -> [String] {
        [
            "## How these numbers were produced",
            "",
            "1. \(result.samples) questions were scored; each was generated from a chunk sampled at random from the collection `\(result.collection)`. Lockfiles, minified and generated files are excluded.",
            "2. Each chunk's identifiers were split into plain words (camelCase/snake_case, stop-words removed) and the most frequent 4–6 became the question — the vocabulary a developer would type, never a literal string copied from the code.",
            "3. The file the chunk came from is the **ground truth**. " + (result.workspaceVerified == false
                ? "The `find` pass that normally verifies ground-truth files exist under the workspace **timed out on this folder and was skipped** for this run."
                : "Before the duel, one `find` pass verified every ground-truth file exists under the workspace — if the folder does not match the collection, the benchmark refuses to run instead of faking a win."),
            "4. Both engines got the **same query**. grep plays its competent game, not a strawman: first the classic AND pipeline — files containing EVERY query word (longest word first), candidates ranked by how densely the words hit each file; a one-pass OR alternation is the fallback when no file contains them all. It runs from the folder the collection actually indexes. Semantic = embed the query, search the local Qdrant index, rank the distinct files returned.",
            "5. grep timings include normal filesystem caching; the embedding model was pre-warmed before timing, as it is in real use. Each grep had a 15 s budget for its whole strategy; runs that exceeded it are marked and excluded from latency medians.",
            "6. Full disclosure of the construction: the query words come from a chunk of the ground-truth file, so every word is literally present in the answer — grep's AND pipeline can always reach that file. The duel therefore measures **ranking under noise and time to a reviewed answer**, not paraphrase understanding (where literal search cannot compete at all)."
                + (result.paraphrased == true
                    ? " **This run used synonym mode**: one word of each question was swapped for a synonym from a fixed table in the source code (word → next in its group — no runtime cherry-picking). The swapped word is no longer guaranteed to appear in the answer file, so this IS the paraphrase discipline; one swap keeps the question anchored to its file. Every swap is listed under its question."
                    : ""),
            "",
        ]
    }

    private static func verdict(_ result: RetrievalBenchmark) -> [String] {
        let s = result.summary.semantic
        let g = result.summary.grep
        let allTimedOut = (g.timeouts ?? 0) >= result.samples
        let grepTimeCell = allTimedOut
            ? "n/a — every run was stopped at the 15 s budget" : ms(g.medianLatencyMS)
        let grepLinesCell = (g.medianMatchedLines ?? 0) <= 0
            ? "n/a — no completed run matched anything" : "\(int(g.medianMatchedLines ?? 0)) matching lines (median)"
        var lines = [
            "## Verdict",
            "",
            "| Metric | grep -riE | Embarsy semantic |",
            "|---|---|---|",
            "| Right file in top-\(result.topK) | \(g.hitTopK)/\(result.samples) | \(s.hitTopK)/\(result.samples) |",
            "| Right file ranked #1 | \(g.hitTop1)/\(result.samples) | \(s.hitTop1)/\(result.samples) |",
            "| Median time to a ranked answer | \(grepTimeCell) | \(ms(s.medianLatencyMS)) |",
            "| To sift through, per question | \(grepLinesCell) | \(result.topK) ranked snippets |",
        ]
        if let timeouts = g.timeouts, timeouts > 0 {
            lines.append("| grep runs stopped at the 15 s budget | \(timeouts) | — |")
        }
        if let zeroes = g.zeroResultQueries, zeroes > 0 {
            lines.append("| grep queries with zero matches | \(zeroes) | — |")
        }
        if result.meaningWins > 0 {
            lines.append("")
            lines.append("**Meaning won \(result.meaningWins) of \(result.samples):** in those questions grep found files matching the query words — and the right file still never reached its top-\(result.topK). The semantic index ranked it by meaning.")
        }
        lines.append("")
        return lines
    }

    private static func questionSection(index: Int, row: BenchmarkQueryRow, topK: Int) -> [String] {
        var lines = [
            "### Q\(index + 1) · “\(row.query)”",
            "",
            "Ground truth: `\(row.truthFile)`\(row.meaningWins ? " · **meaning wins**" : "")",
            "",
        ]
        if let swaps = row.swapped, !swaps.isEmpty, let original = row.originalQuery {
            lines.append("Synonym swaps: " + swaps.map { "\($0.from) → \($0.to)" }.joined(separator: " · ")
                         + " (originally “\(original)”)")
            lines.append("")
        }

        // grep side
        let strategyNote = row.grep.strategy == "or" ? " · OR fallback (no file contains every word)" : ""
        lines.append("**grep** — \(row.grep.timedOut == true ? "stopped at the 15 s budget" : ms(row.grep.latencyMS))\(strategyNote)")
        if let command = row.grep.command {
            lines.append("```")
            lines.append(command)
            lines.append("```")
        }
        let files = row.grep.filesWithMatches ?? 0
        let matched = row.grep.matchedLines ?? 0
        lines.append("- matched \(int(Double(matched))) lines across \(files) files\(row.grep.timedOut == true ? " (before it was stopped)" : "")")
        if row.grep.truncatedOutput == true {
            lines.append("- grep's output overflowed the 8 MB capture cap — these counts are lower bounds")
        }
        if let top = row.grep.topMatches, !top.isEmpty {
            lines.append("- top files by matching lines:")
            for (position, match) in top.enumerated() {
                lines.append("  \(position + 1). `\(match.path)` — \(match.lines) lines\(marker(match.path, truth: row.truthFile))")
            }
        } else if !row.grep.topFiles.isEmpty {
            lines.append("- top files: " + row.grep.topFiles.enumerated()
                .map { "\($0 + 1). `\($1)`\(marker($1, truth: row.truthFile))" }
                .joined(separator: " · "))
        }
        lines.append("- ground truth: \(verdictLine(rank: row.grep.rank, topK: topK))")
        lines.append("")

        // semantic side
        var semanticHeader = "**Embarsy semantic** — \(ms(row.semantic.latencyMS))"
        if let embed = row.semantic.embedMS, let search = row.semantic.searchMS {
            semanticHeader += " (embed query \(ms(embed)) + vector search \(ms(search)))"
        }
        lines.append(semanticHeader)
        if !row.semantic.topFiles.isEmpty {
            lines.append("- top files by meaning:")
            for (position, path) in row.semantic.topFiles.enumerated() {
                lines.append("  \(position + 1). `\(path)`\(marker(path, truth: row.truthFile))")
            }
        }
        if let chars = row.semantic.snippetChars, chars > 0 {
            lines.append("- context returned: \(min(topK, row.semantic.topFiles.count)) snippets, \(int(Double(chars))) chars (≈ \(int(Double(chars) / 4)) tokens)")
        }
        lines.append("- ground truth: \(verdictLine(rank: row.semantic.rank, topK: topK))")
        lines.append("")
        return lines
    }

    private static func duelSection(duels: [AgentDuel], editor: BenchmarkEditor) -> [String] {
        var lines = [
            "## Live editor duels — \(editor.title)",
            "",
            "The same questions answered end-to-end by the local \(editor.title) agent: once restricted to grep-style tools, once leading with Embarsy's `search_code` (MCP). Wall-clock seconds and tokens are what the user actually pays. The condition order alternated per question so neither side always ran on a warm filesystem cache.",
            "",
        ]
        for (index, duel) in duels.enumerated() {
            lines.append("### Duel \(index + 1) · “\(duel.question)”")
            lines.append("")
            lines.append("Ground truth: `\(duel.truthFile)`")
            lines.append(agentLine(label: "grep-only", run: duel.grepRun))
            lines.append(agentLine(label: "with Embarsy", run: duel.semanticRun))
            lines.append("")
        }
        return lines
    }

    private static func agentLine(label: String, run: AgentRun) -> String {
        var parts = ["- **\(label)**: "]
        if let note = run.failureNote, run.answer.isEmpty {
            parts.append("failed (\(note)) after \(seconds(run.seconds))")
        } else {
            parts.append(run.correct ? "✔ correct" : "✘ wrong")
            parts.append(" — answered `\(run.answer.isEmpty ? "(no path in reply)" : run.answer)` in \(seconds(run.seconds))")
            if let tokens = run.totalTokens {
                parts.append(", \(int(Double(tokens))) tokens of context/output")
            }
            if let note = run.failureNote {
                parts.append(" (\(note))")
            }
        }
        return parts.joined()
    }

    private static func notes(_ result: RetrievalBenchmark) -> [String] {
        [
            "## Notes for the skeptical",
            "",
            "- Every grep command above is copy-pasteable: run it from `\(result.grepRoot ?? result.workspacePath)` to reproduce the counts (results can drift as the code changes; rows marked as stopped or capped are lower bounds). AND stages execute as separate processes for timeout control — the shell pipeline shown is the reproducible equivalent.",
            "- Token estimates use the ~4 chars/token heuristic; agent duels report the CLI's own usage numbers instead when available.",
            "- \(result.samples) sampled questions are an indication, not a paper. Run the benchmark again for a fresh random sample — the shape of the result is what matters, not a single decimal.",
            "",
        ]
    }

    // MARK: Formatting

    private static func marker(_ path: String, truth: String) -> String {
        BenchmarkService.pathsMatch(path, truth) ? "  ← ground truth" : ""
    }

    private static func verdictLine(rank: Int?, topK: Int) -> String {
        rank.map { "ranked **#\($0)**" } ?? "**not in the top-\(topK)**"
    }

    private static func ms(_ value: Double) -> String {
        value >= 1000 ? String(format: "%.2f s", value / 1000) : String(format: "%.0f ms", value)
    }

    private static func seconds(_ value: Double) -> String {
        String(format: "%.0f s", value)
    }

    private static func int(_ value: Double) -> String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.groupingSeparator = " "
        return formatter.string(from: NSNumber(value: Int(value))) ?? String(Int(value))
    }
}
